import { Component3DData } from "../../abstract/component-3d-data";
import { XYZ } from "../types";
import { Mesh, Object3D } from "three";

/**
 * @public
 *
 * Data interface for {@link ObjectComponent}.
 *
 * Defines the configuration for a component that wraps a Three.js {@link Object3D} with
 * full {@link Component3D} capabilities — including collision mesh generation, interaction,
 * physics, and transform management. When an `object` is provided, the component
 * automatically attaches it to the scene and derives a collision mesh from its geometry.
 *
 * The component can also be used without an `object` to create behavior-only nodes in the
 * scene — for example, script hosts, control logic containers, or empty parent nodes for
 * grouping child components.
 *
 * Because this component extends {@link Component3DData}, it supports standard transform
 * properties (`position`, `rotation`, `scale`) as well as optional `collider` and `script`
 * configuration inherited from the base data interface.
 *
 * This component is not serializable (object data property is not serializable). It can be created only at runtime.
 *
 * See {@link ComponentManager.create} for how to create a component at runtime.
 */
export interface ObjectComponentData extends Component3DData {
  /**
   * @internal
   */
  kit?: "cyber";

  /**
   * Component type identifier. Must be `"object"`.
   */
  type: "object";

  /**
   * if not provided, an auto id will be generated
   */
  id?: string;

  /**
   * name for the component. Defaults to ""
   */
  name?: string;

  /**
   * An optional Three.js `Object3D` to attach to this component.
   *
   * When provided, the component automatically adds the object to the scene and
   * provides full {@link Component3D} facilities — including collision mesh generation
   * from the object's geometry, interaction handling, transform management, and physics.
   *
   * This property is runtime-only (Object3D is not serializable). The component must
   * be created programmatically via {@link ComponentManager.create}.
   */
  object?: Object3D;

  /**
   * An optional custom collision mesh to use instead of the default one
   * auto-generated by merging the geometries of the attached `object`.
   *
   * When provided, {@link ObjectComponent.getCollisionMesh} returns this mesh
   * directly, skipping the geometry merge step. Useful when the merged geometry
   * is too detailed or when a simpler collision shape is needed.
   *
   * This property is runtime-only (Mesh is not serializable). The component must
   * be created programmatically via {@link ComponentManager.create}.
   */
  collisionMesh?: Mesh;
}
