/**
 * @public
 */
export const Bones = [
    "chest",
    "head",
    "hips",
    "jaw",
    "leftEye",
    "leftFoot",
    "leftHand",
    "leftIndexDistal",
    "leftIndexIntermediate",
    "leftIndexProximal",
    "leftLittleDistal",
    "leftLittleIntermediate",
    "leftLittleProximal",
    "leftLowerArm",
    "leftLowerLeg",
    "leftMiddleDistal",
    "leftMiddleIntermediate",
    "leftMiddleProximal",
    "leftRingDistal",
    "leftRingIntermediate",
    "leftRingProximal",
    "leftShoulder",
    "leftThumbDistal",
    "leftThumbMetacarpal",
    "leftThumbProximal",
    "leftToes",
    "leftUpperArm",
    "leftUpperLeg",
    "neck",
    "rightEye",
    "rightFoot",
    "rightHand",
    "rightIndexDistal",
    "rightIndexIntermediate",
    "rightIndexProximal",
    "rightLittleDistal",
    "rightLittleIntermediate",
    "rightLittleProximal",
    "rightLowerArm",
    "rightLowerLeg",
    "rightMiddleDistal",
    "rightMiddleIntermediate",
    "rightMiddleProximal",
    "rightRingDistal",
    "rightRingIntermediate",
    "rightRingProximal",
    "rightShoulder",
    "rightThumbDistal",
    "rightThumbMetacarpal",
    "rightThumbProximal",
    "rightToes",
    "rightUpperArm",
    "rightUpperLeg",
    "spine",
    "upperChest"
] as const;

/**
 * @public
 */
export type Bone = typeof Bones[number];