
export default {
    sunshine:
        "https://cyber.mypinata.cloud/ipfs/QmQdEGgHE75rtiC3rppPnbmPauVG7qMiaB6wFdu9aobp9R?filename=sunshine.glb",
    pepe:
        "https://cyber.mypinata.cloud/ipfs/Qmf7RQDNPffqdiC47reQ3iZeAFqMmP8thwfBqyj4eyfsWr?filename=pepe.glb",
    square:
        "https://cyber.mypinata.cloud/ipfs/QmX7XfjWmKPXYe6eX9Kr719JtgiGMJe8iNt1YEJDdpTMhG?filename=square.glb",
    check:
        "https://cyber.mypinata.cloud/ipfs/QmYrwgJc2iqZyJ76azoqSDt7t3V28FxyeoVKNihiTWB6NM?filename=check.glb",
    alienking:
        "https://cyber.mypinata.cloud/ipfs/QmRbQMQkC1xerFdLeT8vH3SLWdAjvj1T59VskdhFfTJFow?filename=1692887729-1692887728.052.vrm",
    tottori:
        "https://cyber.mypinata.cloud/ipfs/QmW9vHifS3jZzRb9mpHjfyiptEQzv6HDjWxV3YTXc2hGE5?filename=1692885790-1692885789.482.vrm",
    chimpers:
        "https://cyber.mypinata.cloud/ipfs/Qmcdp2oGeD66QF9KSkAyUnVEfEaUG36RMABNFMCSKB4oA9?filename=1692886018-1692886017.557.vrm",
    ozohr:
        "https://cyber.mypinata.cloud/ipfs/QmZidf9GvizcnZXYohGyqRjNJM226fsf25fcnFk6vJWNHY?filename=1692636853-1692636853.039.vrm",
    smowl:
        "https://cyber.mypinata.cloud/ipfs/QmT7pfxjZQmmoyiokAe2AB3VrWJKyZXvskKm4px96LyfHL?filename=1692636911-1692636910.82.vrm",
    mfer:
        "https://cyber.mypinata.cloud/ipfs/QmQY6a4vuNeikm4QB8QYvAeQ6NKnuRm91gyzQzZG9CCpgc?filename=1692636949-1692636948.38.vrm",
    bunny:
        "https://cyber.mypinata.cloud/ipfs/QmdNmPt1UGcZwXVAjWGpxGverqWjZ3gPBbDNnQ5gBrXLaR?filename=1692637197-1692637196.574.vrm",
    fred:
        "https://cyber.mypinata.cloud/ipfs/QmeyWHKrvBKYMuDtWBYjQgKXnvZFy3DGFkRWe53ExvRiSp?filename=1692637046-1692637044.848.vrm",
    void2045:
        "https://cyber.mypinata.cloud/ipfs/QmWBorKXQSn51F2MBxtCsntJotiXk6uVGrsxLxSUjjCL6u?filename=1693484976-1693484975.664.vrm",
    "cool-steak":
        "https://cyber.mypinata.cloud/ipfs/QmVTCaEnnyvZ8HFKd6rqtbsSjCtoNtGdCdLAS2p5xLTQPm?filename=cool-steak.glb",
    "cool-cloud":
        "https://cyber.mypinata.cloud/ipfs/QmQmmS5NJ21yQo8DNaryxghuuhaL6BdMsBvnMUV9BPaTLL?filename=cool-cloud.glb",
    chilli:
        "https://cyber.mypinata.cloud/ipfs/QmZNB77Z7V41X1quvW7Ri9NMi6RYBywTnziXvaDTWPFNjL?filename=chilli.glb",
    retroman:
        "https://cyber.mypinata.cloud/ipfs/Qmc3TkmcnLyFTtfYwmzFdBP9bxTWtfZdgzxCLrnEJ6UaDF?filename=retroman.glb",
    froggy:
        "https://cyber.mypinata.cloud/ipfs/QmTUGp5hmqsm1ymCFYV9jmS7bStN47HXcLX8zFizLurWC9?filename=froggy.glb",
    astrodisco:
        "https://cyber.mypinata.cloud/ipfs/QmebsFg57VYWz2pbqz32E7FC7bkapvzre5xwEGPhZWZTmd?filename=astrodisco.glb",
    "cool-asparagoose":
        "https://cyber.mypinata.cloud/ipfs/QmW4ToEy3ZgRhNe9pYAxVWmdPZ8anDEdBwf2vr6W3MWRQH?filename=cool-asparagoose.glb",
    "super-sup":
        "https://cyber.mypinata.cloud/ipfs/QmcuTLNh19EdYpZbWFaA5hdexwmw2AtvG9B3z5G4tzDXHn?filename=super-sup.glb",
    devil:
        "https://cyber.mypinata.cloud/ipfs/QmaTwtSfBN55RgfohaXAi95iRHzGdBvYzgrmJzCHiQfqV3?filename=devil.glb",
    "cool-poo":
        "https://cyber.mypinata.cloud/ipfs/QmdL8LbcK8HPDJgKtBiZbYxzPBro3wC4rAzDAyhwWjQdR3?filename=cool-poo.glb",
    pumpkin:
        "https://cyber.mypinata.cloud/ipfs/QmTdK6Pu6WBQuDNYhhYF1Mjx3QPiXiLJhvqaAntYPyRhkr?filename=pumpkin.glb",
    "cool-drumstick":
        "https://cyber.mypinata.cloud/ipfs/QmWEWTehzhPkcq7LQwE2EEJH6oiCaQZir38AoiscA8dF2p?filename=cool-drumstick.glb",
    "cool-loops":
        "https://cyber.mypinata.cloud/ipfs/QmTYahw6VJw51j2bRGBMgKP2tdG3xC5DWNXQ6t3nZCfnNf?filename=cool-loops.glb",
    "saint-claus":
        "https://cyber.mypinata.cloud/ipfs/QmQmtdSnmopUdDJCN5ygtUh7mkvN8cZsDZfnEvq44VzMWw?filename=saint-claus.glb",
    rabbit:
        "https://cyber.mypinata.cloud/ipfs/QmcoLDMXzR6DNoaR4JFiWAQiZrdi7SVgHwcnAf6iL6azyp?filename=rabbit.glb",
    "cool-cola":
        "https://cyber.mypinata.cloud/ipfs/QmVhgHMCVcVeBJJ5jQ3KYJbnkY5UG477zWrU1RR1AakaEH?filename=cool-cola.glb",
    "cool-pan":
        "https://cyber.mypinata.cloud/ipfs/QmcC3dgqik2aQDu3UDSuf4CvCTGFU38hY2KHUqFvCzNAyp?filename=cool-pan.glb",
    "cool-egg":
        "https://cyber.mypinata.cloud/ipfs/QmW9N8fdiUuBUfLMWfa3TjrkdWgd1sZEEVpp1346FtuD4x?filename=cool-egg.glb",
    fungus:
        "https://cyber.mypinata.cloud/ipfs/QmdRuggpi5nERib32dQF9y9PAnDuGrrtPpitQSRiC8hvC5?filename=fungus.glb",
    "circle-boi":
        "https://cyber.mypinata.cloud/ipfs/QmfNPmLf8whCLpFkCwcnNN2y1L8Lzc4ZStPFLD9bWAzeyf?filename=circle-boi.glb",
    "cool-ketchup":
        "https://cyber.mypinata.cloud/ipfs/Qmc4KknP6edHLNbunBS35R4wuLFUfHYTKhd6sNrkPAuxe9?filename=cool-ketchup.glb",
    "ban-hammer-dude":
        "https://cyber.mypinata.cloud/ipfs/QmfBSZh8B2B9tsmc8Qt4nEjBYbK92uHQQB7o8VYq2qNpcn?filename=ban-hammer-dude.glb",
    baldman:
        "https://cyber.mypinata.cloud/ipfs/QmSF7KKULRtkWTMRJ2rqEXPwiRSAt2RY4HvEZ4RS3M6fPP?filename=baldman.glb",
    cucumber:
        "https://cyber.mypinata.cloud/ipfs/QmebA61MErdLqQXLsP34ekZtEVmmtDB9U9BYDtHq5VfH9G?filename=cucumber.glb",
    sticker:
        "https://cyber.mypinata.cloud/ipfs/Qmc5uGrPg9Gx48xw3FeSf2mKMwuUqu1fYYPge7RTxbeKW4?filename=sticker.glb",
    mowchok:
        "https://cyber.mypinata.cloud/ipfs/QmPakbDW6fBE7JF8Vm2zcoyKZyb9M6wzeYoEcRXgGAKNy8?filename=mowchok.glb",
    expol:
        "https://cyber.mypinata.cloud/ipfs/QmTmsJLWZibqWZHh7LEP5YntSfd8dTSGPEbjBtMGFTk3mY?filename=expol.glb",
    avocado:
        "https://cyber.mypinata.cloud/ipfs/QmNhvLzeZAAWmA7bMs21ULTFNeSzRvsFyWYBh7ZJMaoRpc?filename=avocado.glb",
    skull:
        "https://cyber.mypinata.cloud/ipfs/QmXKSKS1Xqt4pftSDkj8Zvk7HWte1u8dYx1YAJpm2VywZo?filename=skull.glb",
    mafiossini:
        "https://cyber.mypinata.cloud/ipfs/QmNpBg9UdWWDxYL9iwsDKbQGPUzA71qKKycEk4C3jLhcx4?filename=mafiossini.glb",
    "slug-person":
        "https://cyber.mypinata.cloud/ipfs/QmSMNUVoveDaBeVLRLfUX89Vx72HU9FG8X1pG78kmoqNDH?filename=slug-person.glb",
    "cool-mail":
        "https://cyber.mypinata.cloud/ipfs/Qme5jesNWqhwBcfm7n9g9ZeZyAz8VP8FuQ4v9kj6d58mW1?filename=cool-mail.glb",
    cappy:
        "https://cyber.mypinata.cloud/ipfs/QmSevaL83HGkDZutwW4YrreqLYVifFuk5VRiquAoAfb1hX?filename=cappy.glb",
    "cool-barrel":
        "https://cyber.mypinata.cloud/ipfs/QmYy1gza1kumRJ7XPWbTvNf1tL4qbbkgR1s12Zc3NotKoG?filename=cool-barrel.glb",
    ghost:
        "https://cyber.mypinata.cloud/ipfs/QmXxNmd24MVvJWYjEde6DXft2pjajCTS9Wdxn2bzRkLPEw?filename=ghost.glb",
    "cool-fridge":
        "https://cyber.mypinata.cloud/ipfs/QmaHHXmena1Em7XpWTDoW7H4w5LeCgecwBRSDAeiwaZrZp?filename=cool-fridge.glb",
    scarecrow:
        "https://cyber.mypinata.cloud/ipfs/QmdxFhRK8qJoy9Ziqnbc5XXTiPcZdEo1Fbp7vVLYTwNZgs?filename=scarecrow.glb",
    amazonas:
        "https://cyber.mypinata.cloud/ipfs/QmWPR1cJRyafSWvnZvraJVycpCTABKSqzpCCztQHPum56Y?filename=amazonas.glb",
    "cool-battery":
        "https://cyber.mypinata.cloud/ipfs/QmQ9bUA7HQqFmJTDKmGqELDXSHDmh2gXBkb3kM5G68hZo4?filename=cool-battery.glb",
    "slim-ringo":
        "https://cyber.mypinata.cloud/ipfs/QmYzDMEWSfXdJ6jNJWuELTHKA3xiEtZ6XYmeFRcDPrCftD?filename=slim-ringo.glb",
    "big-bro":
        "https://cyber.mypinata.cloud/ipfs/QmWx8rrYqKmLS5eND82e9rM8xs6bpMDTe3YWu7JffwmjVN?filename=big-bro.glb",
    robothead:
        "https://cyber.mypinata.cloud/ipfs/QmXvcMdzqqpEj7D6V8a6tB1AgvPwfuhsNmW1UoWDSdLPqc?filename=robothead.glb",
    chad:
        "https://cyber.mypinata.cloud/ipfs/QmTA25SMZ2niQJq3J1mTR5ogs7ZYjhbAvzTRfra3oaVJSB?filename=chad.glb",
    "cool-plunger":
        "https://cyber.mypinata.cloud/ipfs/QmSvMFTY93mx6qTrJwzA11aZSmoZs7EAigDdYMDkawcm8Q?filename=cool-plunger.glb",
    "toilet-paper":
        "https://cyber.mypinata.cloud/ipfs/QmWP3pUQYQYLjowtwCCCPzLfhbG2GoJgUpV4SUDYH9ey3S?filename=toilet-paper.glb",
    "chaotic-ozul":
        "https://cyber.mypinata.cloud/ipfs/QmbSkFVLL2eSjbgvHRxUEnFu4SpVZw1GoXixyLG4ZYRmup?filename=chaotic-ozul.glb",
    "unicorn-person":
        "https://cyber.mypinata.cloud/ipfs/QmVtcNP9QYyoR78ZAH34YZL3gbQU9m9ipVzAnivigRa6Zb?filename=unicorn-person.glb",
    "cool-shield":
        "https://cyber.mypinata.cloud/ipfs/QmXHwzzgeJEbu1kXGhJiEe73ETJfcvTuFkcUcrSCoVdAR7?filename=cool-shield.glb",
    wizzir:
        "https://cyber.mypinata.cloud/ipfs/QmX1Pukw9Vzbo9sFBLKudBQa2m2CU92N1cEMtQ2ERh3EmL?filename=wizzir.glb",
    "real-cake":
        "https://cyber.mypinata.cloud/ipfs/QmdrkQLMMYDUfbU5MjsDYMJY9S59gWPXSgCvpi2zhbBstL?filename=real-cake.glb",
    david:
        "https://cyber.mypinata.cloud/ipfs/QmZoD5mK8GHSnHcgYWoshMQre7U8peU63aNCpGqVxNMS2D?filename=david.glb",
    butter:
        "https://cyber.mypinata.cloud/ipfs/QmctMtBrbuTm35ZvL7eJ1FskbqhKKiUpYMgv3oJdo415tg?filename=butter.glb",
    clown:
        "https://cyber.mypinata.cloud/ipfs/QmcM7bRqZuTbXjzfsqm3n4vvGqwDQ6C7VUPWSEyqW6NGKr?filename=clown.glb",
    "cool-money-bag":
        "https://cyber.mypinata.cloud/ipfs/QmdcnJQmX5K6LGdpGQpT9ZN3GUkWdru3HmRPU7M3yQB3b2?filename=cool-money-bag.glb",
    mummy:
        "https://cyber.mypinata.cloud/ipfs/QmNNHn6JjWbnKzw1DJvvY28ri1nkLVK4ASHNGHeSaCkjeM?filename=mummy.glb",
    "cool-stickman":
        "https://cyber.mypinata.cloud/ipfs/Qmdv4qEm9p4UdVjQHe2Dv7NPRan72y64QtYxgC8VrhiDnG?filename=cool-stickman.glb",
    "wire-friend":
        "https://cyber.mypinata.cloud/ipfs/QmY45D2vHopFyMtpinR8cTyiq27A6Tz1oD4BXim6EpR74k?filename=wire-friend.glb",
    pipe:
        "https://cyber.mypinata.cloud/ipfs/QmfKtrBc857kkHTXmgLD2AmZwBeM1ApdeLz7py8EEPM5CH?filename=pipe.glb",
    "shark-person":
        "https://cyber.mypinata.cloud/ipfs/QmZYgzBs7FMsvBsn3o88D2BcwHdaAZvLGwefCMWC93S8SE?filename=shark-person.glb",
    "captain-lantern":
        "https://cyber.mypinata.cloud/ipfs/Qme5URyK3ZB2CYk6SNPaXg6HWXvy1c6tyn9cxeF1Pq8yJu?filename=captain-lantern.glb",
    "always-watching":
        "https://cyber.mypinata.cloud/ipfs/QmXoayBPvXAbdE3icAPZ1hwLezRfqyvF2QHNmSnaAbmni9?filename=always-watching.glb",
    "old-moustache":
        "https://cyber.mypinata.cloud/ipfs/QmUezZ8eQb7dbU2FGjkzgqy6XrR7W32PYD9nnPVS5yJFoZ?filename=old-moustache.glb",
    "conehead-being":
        "https://cyber.mypinata.cloud/ipfs/QmXBFHsbQCyqz9UZKYSaBYmiZCiVqQ4ex1Vtc5TTeprpSA?filename=conehead-being.glb",
    hotdog:
        "https://cyber.mypinata.cloud/ipfs/QmWxNSf5TkiU1SW5LR3UumKYg5vRTWt17cMYpHgHg2YmQC?filename=hotdog.glb",
    samuela:
        "https://cyber.mypinata.cloud/ipfs/QmcK8qfWxvZVn25bYRJamGHcwUBQvLWGNeqMKiZrpW4RSz?filename=samuela.glb",
    "cool-broom":
        "https://cyber.mypinata.cloud/ipfs/QmebjmmdsHjN9zT8C6ZR78GFMQi6sDNUuDKTHtLx8HM2C4?filename=cool-broom.glb",
    "wop-wop":
        "https://cyber.mypinata.cloud/ipfs/QmYPhd3tHikMFhH7fzT31Nhng7kfAjtB2FtYjr1AhH78ke?filename=wop-wop.glb",
    "coffee-maker":
        "https://cyber.mypinata.cloud/ipfs/QmWVgJ8Xw2KhFXSyWvLkcxVYmZKxqhPTCPz1ykNHhDka4R?filename=coffee-maker.glb",
    "tasty-sandwich":
        "https://cyber.mypinata.cloud/ipfs/QmdCCdz5MKN15upmerYRKRCit5BtQWUJv6zgS9hkbAuehu?filename=tasty-sandwich.glb",
    "hodler-king":
        "https://cyber.mypinata.cloud/ipfs/QmQVJjw4VuPg2XxTkZBNqfhR3rhqLHCgBcLvGBmGiK2SMo?filename=hodler-king.glb",
    wambo:
        "https://cyber.mypinata.cloud/ipfs/QmboCwKk3gQS8URwgmz6u3cQbizzKCkf6dYpXvhPEN2vyG?filename=wambo.glb",
    "mister-contract":
        "https://cyber.mypinata.cloud/ipfs/QmTNPepp2LwANHDG9dmouGGkUg9s9AUSporyYx2ixu6qRt?filename=mister-contract.glb",
    "lil-bro":
        "https://cyber.mypinata.cloud/ipfs/QmZinTQHb1zEjq9yC2XTQWJesYk3g2CiUGRemYqi17Hj19?filename=lil-bro.glb",
    kate:
        "https://cyber.mypinata.cloud/ipfs/QmSSGKjiDmnTfds5NTqh3nqz7X4RRFzvPGNqidtdjLbKfp?filename=kate.glb",
    polydancer:
        "https://cyber.mypinata.cloud/ipfs/QmTHMrPZrQHxGoRDYvfn7MDoSvNCwZQVf16ThTK9msEKGC?filename=polydancer.glb",
    mushy:
        "https://cyber.mypinata.cloud/ipfs/QmXG8megzzXBr2RdmQvxaubZVCQCDgXRX994PkfKt6Qfg6?filename=mushy.glb",
    "mighty-isak":
        "https://cyber.mypinata.cloud/ipfs/QmYBpYmrJAwgD5Cn9Tzew4MFk2a1zNYNGUuxbrP1K9HVhf?filename=mighty-isak.glb",
    "cylinder-head":
        "https://cyber.mypinata.cloud/ipfs/QmaNAWoboYwpm65TE4vVNnxUfrLgvgJrVgNBLzzYTXrygs?filename=cylinder-head.glb",
    "candy-cane":
        "https://cyber.mypinata.cloud/ipfs/QmZxF7488XYftpkfCKv3wqVCznPonEutUSvNp5epsXLynp?filename=candy-cane.glb",
    "cool-orange":
        "https://cyber.mypinata.cloud/ipfs/QmRCNJco186u41aFA9NUF6MD64kpveELntTz1vThQ7waA3?filename=cool-orange.glb",
    "cool-choco":
        "https://cyber.mypinata.cloud/ipfs/QmXJLmKJB5mZndy2GHJSuUqfsufzjkZcugD2qKb13D1SiJ?filename=cool-choco.glb",
    "pencil-being":
        "https://cyber.mypinata.cloud/ipfs/QmPTEXyaFzMeKCgkFQqi6uQuntP4LjPPY5rhHEdsmGr1bP?filename=pencil-being.glb",
    "bubble-boi":
        "https://cyber.mypinata.cloud/ipfs/QmdM91TT5ErdTiu7RsNb8NHtDpC7dhzztaeSQQP1LPM4Cg?filename=bubble-boi.glb",
    "ice-cream":
        "https://cyber.mypinata.cloud/ipfs/Qmd7thrkSHv5xFeJFLKKZke3bdDgFM8FSTdAndtxBCu5DK?filename=ice-cream.glb",
    "cool-trash":
        "https://cyber.mypinata.cloud/ipfs/QmR5cbqu2TgtbxGSGJ8E9KjiDkXz2mR7mT7ZH4hvfSL4Rv?filename=cool-trash.glb",
    "disturbing-eyes":
        "https://cyber.mypinata.cloud/ipfs/QmbHxS1M9HLoHNut7nyBtvLJQFzejyP9HkEApyeqHT9wmE?filename=disturbing-eyes.glb",
    "horror-nurse":
        "https://cyber.mypinata.cloud/ipfs/Qmf8uZXkaSJ2VSsihi1bkJNqRKa3E5ajb4vatfHjbJNcti?filename=horror-nurse.glb",
    "cool-tnt":
        "https://cyber.mypinata.cloud/ipfs/QmQyCkNnZLCuTWXtfvepwh7ffZueZRzCmYchQxAUPn2uYM?filename=cool-tnt.glb",
    bacondude:
        "https://cyber.mypinata.cloud/ipfs/Qmdmoj3wrzLoutNErYsDGgTdEjPw7Gn4aYprh4xc5nCXfJ?filename=bacondude.glb",
    eyelids:
        "https://cyber.mypinata.cloud/ipfs/Qmbrqe3YBcdTDcKQZb8haVHC272CvDVXTUo2Yj9oeoqCNV?filename=eyelids.glb",
    franky:
        "https://cyber.mypinata.cloud/ipfs/Qmd19HMfoocyeJBhKrwKz8vJocK7Xj3VUNnZw3vhNeFtGY?filename=franky.glb",
    "cool-bell":
        "https://cyber.mypinata.cloud/ipfs/QmQXqsboDF735JbJ8Vyxr7T3AMkbr1STXby7XBJLxmf7wQ?filename=cool-bell.glb",
    "cool-ramen":
        "https://cyber.mypinata.cloud/ipfs/QmPJvRAF8cd3n17S37UVUGkggktsQ23hRRwPh5uFMKuwzK?filename=cool-ramen.glb",
    "cool-cow":
        "https://cyber.mypinata.cloud/ipfs/QmRoLHMX5zVrv1s3cQ94U8WVeNdyjoXYyMfKPsDxWsdbC6?filename=cool-cow.glb",
    "egg-boy":
        "https://cyber.mypinata.cloud/ipfs/QmYGHisR7jpZKwWdkBWKEdZU1Ex9MsSMqpBSm2FY4ivRxp?filename=egg-boy.glb",
    "falcon-dude":
        "https://cyber.mypinata.cloud/ipfs/QmSrBZ1UJ1vvwYLARbW7pABU4zfJtfDasSmdqyE8gXeLk5?filename=falcon-dude.glb",
    "eye-wizard":
        "https://cyber.mypinata.cloud/ipfs/QmWd6nXF1xPmDa7UneHZ1V23UdGSYrBBCRbaUvcPuArymY?filename=eye-wizard.glb",
    "cool-board":
        "https://cyber.mypinata.cloud/ipfs/QmRaNXjBGPDhBjVxapacyHRutfojvCvgfbkywLXgBzXKKt?filename=cool-board.glb",
    "lup-lup":
        "https://cyber.mypinata.cloud/ipfs/Qme2646K5opZyYQLWTcgBnsB2TYUuGka74DgG7VJJU6Dnw?filename=lup-lup.glb",
    erika:
        "https://cyber.mypinata.cloud/ipfs/QmQvAPefmmrVSPW44K7na9zXc2nUVhcinNgQaS6ko3DYv7?filename=erika.glb",
    pepo:
        "https://cyber.mypinata.cloud/ipfs/QmSsoeG4quN15qJ78LopawUY3TMC4EeGuWfmzqquptS3q3?filename=pepo.glb",
    kyle:
        "https://cyber.mypinata.cloud/ipfs/QmczHb813dDqAF99VkcqTGLHcz8EMmBkRg2CGLrFaPGGVr?filename=kyle.glb",
    "hourglass-person":
        "https://cyber.mypinata.cloud/ipfs/QmeT9HippHGBiHo5SHRCmoP6UDr4xNTUfXKjheHxEZHygK?filename=hourglass-person.glb",
    wolfman:
        "https://cyber.mypinata.cloud/ipfs/QmX9JcM25PBDDjc4b696wk8TqhMAP3F9K7HqbXpfznZELF?filename=wolfman.glb",
    "cool-baguette":
        "https://cyber.mypinata.cloud/ipfs/QmZkhFcYpbhmBqDYF7Ez7PXX3W2uKEMMJ2PoD7scn8vaY1?filename=cool-baguette.glb",
    "random-boi":
        "https://cyber.mypinata.cloud/ipfs/QmbHwzg4DQPuu7WXyPFRvMWHUpbtfvw54f752dZDxjjiY2?filename=random-boi.glb",
    jimmy:
        "https://cyber.mypinata.cloud/ipfs/QmVjTSMgUPgegaQwbZe29RSowFta3Eu7aPim8gZS856LPs?filename=jimmy.glb",
    "dope-screwdriver":
        "https://cyber.mypinata.cloud/ipfs/QmS1jps5PcJfTPkYUghvxVLecNbPwMT2KdumVQXxooSGeH?filename=dope-screwdriver.glb",
    angry:
        "https://cyber.mypinata.cloud/ipfs/QmYip27uAmqXULd2mnVHQynScZXvwrr2JbWek2FVYocngg?filename=angry.glb",
    "cool-bunny":
        "https://cyber.mypinata.cloud/ipfs/QmUrtcNBMh13aGkSLzg4jXw1AhvVcHcrHuwPtq39zSMeWy?filename=cool-bunny.glb",
    "cool-pizza":
        "https://cyber.mypinata.cloud/ipfs/QmVUJLWLMLRW8kQ5iy9aUda524hDu83dfBhavF6DMGDzKs?filename=cool-pizza.glb",
    "eye-cleric":
        "https://cyber.mypinata.cloud/ipfs/QmWgbZGaqvsLj6vmMN1RCK1JUgJWPcXxjSKDoBUJtJduD1?filename=eye-cleric.glb",
    "cool-drink":
        "https://cyber.mypinata.cloud/ipfs/QmUohok98U5NEoYWrPnoTFQrYs8Vv7Pec9Kj3kBnabAnFd?filename=cool-drink.glb",
    lalobot:
        "https://cyber.mypinata.cloud/ipfs/QmbX9ogDggSLsVa39hmj5BB42Ttkwk8ypBqPyj7C1LQwYT?filename=lalobot.glb",
    watermelon:
        "https://cyber.mypinata.cloud/ipfs/QmaKFmRanzzHVWhjtgM3rFkCLXnmfbNykvM75n1aA7AERq?filename=watermelon.glb",
    zombie:
        "https://cyber.mypinata.cloud/ipfs/QmUnXZofhqSJCBTrRi9pZE7ED4fGSCFLLG8Gqf7WW9cDtc?filename=zombie.glb",
    "goldfish-bag-person":
        "https://cyber.mypinata.cloud/ipfs/QmQCqtqKU9a6nQKR5g3oR5Kyoc9A378vurvCYc33rdH2Px?filename=goldfish-bag-person.glb",
    "cool-taco":
        "https://cyber.mypinata.cloud/ipfs/QmQSCN9tN3r2ZVL17FZPpq6EHgMxgTzKJxu1F4ASCniC6Z?filename=cool-taco.glb",
    diver:
        "https://cyber.mypinata.cloud/ipfs/QmcXpyhwZWt9jwcsKMLtS8nJf5arfUL7zRmLNfVwGGc2M3?filename=diver.glb",
    "cool-fries":
        "https://cyber.mypinata.cloud/ipfs/QmeHBEhNrTx1afu3ve4Aaq5ebNK85JYhTXXchutTSBDmxt?filename=cool-fries.glb",
    "eye-summoner":
        "https://cyber.mypinata.cloud/ipfs/QmdiKzCiAboqbpuBtmy57YVewaUEUHnLg1wSZPDkzevZu6?filename=eye-summoner.glb",
    "cool-guitar":
        "https://cyber.mypinata.cloud/ipfs/QmS9vL8WxUQkhiSzBhuj4XBpTF7AtqYQAPd3UqCh6JS9hP?filename=cool-guitar.glb"
}