import { Component3DData } from "../../abstract/component-3d-data";

/**
 * Configuration data for the VRM Animations component ({@link VRMAnimsComponent}).
 *
 * Defines which animations are available for VRM avatars in the scene. This includes
 * overriding the six built-in default animations (idle, walk, jump, run, fly, sitting)
 * as well as adding custom animations from FBX files. The component is a singleton —
 * only one instance can exist per scene.
 *
 * Custom animations are referenced by name and can be assigned to avatars via the
 * avatar's animation property (e.g., `avatar.animation = "dance"`).
 *
 * @public
 */
export interface VRMAnimationsComponentData extends Component3DData {
    /**
     * @internal
     */
    kit?: "cyber";

    /**
     * Component type identifier. Must be `"vrm-anims"`.
     */
    type: "vrm-anims";

    /**
     * Optional identifier for the component instance. If not provided, an auto-generated
     * id will be used. Defaults to `"vrm-anims"`.
     */
    id?: string;

    /**
     * URL of a packed animations data file containing pre-baked animation clips.
     * This is typically auto-generated by the studio when uploading animations for
     * the built-in animation slots (idle, walk, jump, run, fly, sitting).
     *
     * Optional — if not provided, only default built-in animations and individually
     * unpacked animations (those with their own URLs in {@link VRMAnimationData.url})
     * are loaded.
     */
    url?: string;

    /**
     * A map of animation definitions keyed by animation slot ID.
     *
     * Built-in animation slots use the IDs: `"idle"`, `"walk"`, `"jump"`, `"run"`,
     * `"fly"`, `"sitting"`. Custom animations use auto-generated keys like
     * `"custom-1"`, `"custom-2"`, etc.
     *
     * Each entry describes an animation's name, playback settings, and source file.
     *
     * Defaults to `{}` (empty — only built-in default animations are used).
     */
    anims?: { [id: string]: VRMAnimationData };
}

/**
 * Describes a single VRM animation entry within {@link VRMAnimationsComponentData.anims}.
 *
 * Each animation has a unique name that can be used to trigger it on VRM avatars (e.g., by
 * setting the avatar's animation property). Animations are sourced from FBX files which are
 * converted and baked into a JSON format for runtime use.
 *
 * @public
 */
export interface VRMAnimationData {
    /**
     * The original file name of the uploaded FBX animation file (e.g., `"dance.fbx"`).
     * Used for display purposes in the studio editor.
     */
    fileName: string;

    /**
     * The display and reference name of the animation. This name is used to trigger the
     * animation on VRM avatars. Names for custom animations must be unique, contain only
     * letters, numbers, underscores, and dashes, and must not start with a number.
     *
     * For built-in slots (idle, walk, etc.), the name matches the slot ID.
     * For custom animations, this can be any valid name (e.g., `"dance"`, `"wave"`).
     */
    name: string;

    /**
     * Whether the animation should loop continuously. When `true`, the animation repeats
     * indefinitely. When `false`, it plays once and stops on the last frame.
     *
     * Defaults to `true` for newly uploaded animations.
     */
    loop: boolean;

    /**
     * The playback speed multiplier for the animation. A value of `1` is normal speed,
     * `0.5` is half speed, and `2` is double speed. Valid range is `0.01` to `4`.
     *
     * Defaults to `1` for newly uploaded animations.
     */
    timeScale: number;

    /**
     * URL of the individual baked animation JSON file. This is set automatically when
     * an animation is uploaded as an unpacked (standalone) animation. Animations with a
     * `url` are loaded independently rather than from the packed data bundle.
     *
     * Optional — packed animations (built-in slots) do not have individual URLs.
     */
    url?: string;

    /**
     * A content hash of the baked animation data, used for deduplication when uploading
     * and merging animations. Automatically generated during the baking process.
     *
     * Optional — may be absent for older animations that predate the hashing feature.
     */
    hash?: string;
}
