import { ParticleBehaviorRegistry } from "../particle-behavior";
import { ScaleBehavior } from "./scale";
import { RotationBehavior } from "./rotation";
import { ColorBehavior } from "./color";
import { NoiseBehavior } from "./noise";
import { SpawnPositionBehavior } from "./spawn-position";
import { MaterialBehavior } from "./material";
import { FrustumTestBehavior } from "./frustum-test";
import { ForcesBehavior } from "./forces";
import { GradientBehavior } from "./gradient";
import { SizeOverLifeBehavior } from "./size-over-life";
import { SpeedOverLifeBehavior } from "./speed-over-life";
import { ShapeEmitterBehavior } from "./shape-emitter";
import { FlipbookBehavior } from "./flipbook";
import { FbmNoiseBehavior } from "./fbm-noise";
import { SoftParticlesBehavior } from "./soft-particles";
import { DepthCollisionBehavior } from "./depth-collision";
import { SortingBehavior } from "./sorting";

ParticleBehaviorRegistry.register(ForcesBehavior as any);
ParticleBehaviorRegistry.register(ScaleBehavior as any);
ParticleBehaviorRegistry.register(RotationBehavior as any);
ParticleBehaviorRegistry.register(ColorBehavior as any);
ParticleBehaviorRegistry.register(NoiseBehavior as any);
ParticleBehaviorRegistry.register(SpawnPositionBehavior as any);
ParticleBehaviorRegistry.register(MaterialBehavior as any);
ParticleBehaviorRegistry.register(FrustumTestBehavior as any);
ParticleBehaviorRegistry.register(GradientBehavior as any);
ParticleBehaviorRegistry.register(SizeOverLifeBehavior as any);
ParticleBehaviorRegistry.register(SpeedOverLifeBehavior as any);
ParticleBehaviorRegistry.register(ShapeEmitterBehavior as any);
ParticleBehaviorRegistry.register(FlipbookBehavior as any);
ParticleBehaviorRegistry.register(FbmNoiseBehavior as any);
ParticleBehaviorRegistry.register(SoftParticlesBehavior as any);
ParticleBehaviorRegistry.register(DepthCollisionBehavior as any);
ParticleBehaviorRegistry.register(SortingBehavior as any);
